### ISSUE TITLE
why the project is empty now?

### ISSUE THREAD

**Issue by 13227018679** [krocki/dnc#3]

**Comment by ENegatiVY** [comment]
I dont know ethier , but you can find similar code in the forked projects https://github.com/krocki/dnc/network/members

**Comment by hg9102** [comment]
@13227018679 'Differentiable Neural Computer in Numpy' is being claimed by IBM and the code is no longer available for research purposes

**Comment by krocki** [comment]
It’s available now, I’ve rewritten it
